import { describe, it, expect } from 'vitest';
import fs from 'fs';
import path from 'path';
import { createCanvas, loadImage } from 'canvas';
import { detectDocumentQuadAsync } from '@/lib/scanner';

// One committed synthetic frame from the scanner corpus (bench/corpus, case
// synth-pos-000: A4 text page on a plain-contrast background, even light, no skew).
// The frame is regenerated byte-identically by `npm run bench:synth`, and its
// ground-truth corners come from the manifest, so this test measures detection
// accuracy against a known quad instead of only checking that four corners came
// back. The full per-condition picture is the benchmark's job (`npm run bench`).

const FIXTURE = path.join(process.cwd(), 'tests/fixtures/scanner/synth-pos-000.jpg');
const MANIFEST = path.join(process.cwd(), 'bench/corpus/manifest.json');
const CASE_ID = 'synth-pos-000';

describe('Document detection on a corpus frame', () => {
  it('finds the page within 3 % of the long edge of the ground truth', async () => {
    const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8')) as { cases: { id: string; quad: [number, number][] | null; width: number; height: number }[] };
    const truth = manifest.cases.find((c) => c.id === CASE_ID);
    expect(truth?.quad).toBeTruthy();

    const img = await loadImage(FIXTURE);
    expect(img.width).toBe(truth!.width);
    expect(img.height).toBe(truth!.height);

    // Live detection sees a 320 px wide downscale (CameraView.tsx); run at that size.
    const w = 320;
    const h = Math.round((img.height * w) / img.width);
    const canvas = createCanvas(w, h);
    const ctx = canvas.getContext('2d');
    ctx.drawImage(img, 0, 0, w, h);
    const imageData = ctx.getImageData(0, 0, w, h) as unknown as ImageData;

    const result = await detectDocumentQuadAsync(imageData, { detector: 'classical' });
    expect(result).not.toBeNull();
    expect(result!.corners).toHaveLength(4);
    expect(result!.confidence).toBeGreaterThan(0.3);

    const longEdge = Math.max(w, h);
    const errors = result!.corners!.map((p, i) => {
      const [tx, ty] = truth!.quad![i];
      return Math.hypot(p.x - tx * w, p.y - ty * h) / longEdge;
    });
    const maxError = Math.max(...errors);
    expect(maxError, `corner errors (fraction of long edge): ${errors.map((e) => e.toFixed(3)).join(', ')}`).toBeLessThan(0.03);
  }, 20000);
});
